[phases.setup]
nixPkgs = ["mailpit"]

[start]
cmd = "mailpit"

[variables]
MP_MAX_MESSAGES_STORED = "1000"
MP_MESSAGE_RETENTION = "168h"
MP_SMTP_PORT = "1025"
MP_SMTP_AUTH_ALLOW_INSECURE = "true"
MP_SMTP_AUTH_ACCEPT_ANY = "true"
